import { hashSync } from "bcryptjs";

const sampleData = {
  users: [
    {
      name: "admin",
      email: "admin@test.com",
      password: hashSync("123456", 10),
      role: "admin",
    },
    {
      name: "user",
      email: "user@test.com",
      password: hashSync("123456", 10),
      role: "user",
    },
  ],
  products: [
    {
      name: "Classic Pullover Hoodie",
      slug: "classic-pullover-hoodie",
      category: "Men's Sweatshirts",
      description: "Soft fleece hoodie with a relaxed everyday fit",
      images: [
        "/images/sample-products/3b.png",
        "/images/sample-products/3bl.png",
      ],
      price: 5980,
      brand: "Polo",
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Plaid Flannel Hoodie",
      slug: "plaid-flannel-hoodie",
      category: "Men's Sweatshirts",
      description: "Cozy flannel hoodie with a classic buffalo check pattern",
      images: [
        "/images/sample-products/2g.png",
        "/images/sample-products/2gr.png",
      ],
      price: 6590,
      brand: "Brooks Brothers",
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: "/images/banner/banner-2.jpg",
    },
    {
      name: "Oxford Dress Shirt",
      slug: "oxford-dress-shirt",
      category: "Men's Dress Shirts",
      description: "A perfect blend of sophistication and comfort",
      images: [
        "/images/sample-products/8b.png",
        "/images/sample-products/8gr.png",
      ],
      price: 9995,
      brand: "Tommy Hilfiger",
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: true,
      banner: "/images/banner/banner-3.jpg",
    },
    {
      name: "Tattersall Check Shirt",
      slug: "tattersall-check-shirt",
      category: "Men's Dress Shirts",
      description: "Streamlined design with flexible stretch fabric",
      images: [
        "/images/sample-products/p3-1.jpg",
        "/images/sample-products/p3-2.jpg",
      ],
      price: 3995,
      brand: "Calvin Klein",
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      banner: "/images/banner/banner-4.jpg",
      isFeatured: false,
    },
    {
      name: "Running Sneakers",
      slug: "running-sneakers",
      category: "Men's Shoes",
      description: "Lightweight mesh sneakers built for everyday comfort",
      images: [
        "/images/sample-products/6g.png",
        "/images/sample-products/6w.png",
      ],
      price: 2999,
      brand: "Nike",
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Nike Sneakers",
      slug: "nike-sneakers",
      category: "Shoes",
      description: "Lightweight mesh sneakers built for everyday comfort",
      images: [
        "/images/sample-products/7g.png",
        "/images/sample-products/7p.png",
      ],
      price: 2999,
      brand: "Nike",
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },

    {
      name: "Pinpoint Oxford Shirt",
      slug: "pinpoint-oxford-shirt",
      category: "Men's Dress Shirts",
      description: "Crisp striped oxford shirt with a button-down collar",
      images: [
        "/images/sample-products/4p.png",
        "/images/sample-products/4w.png",
      ],
      price: 6995,
      brand: "Ralph Lauren",
      rating: 4.4,
      numReviews: 7,
      stock: 14,
      isFeatured: true,
      banner: "/images/banner/banner-5.jpg",
    },
    {
      name: "Denim Western Shirt",
      slug: "denim-western-shirt",
      category: "Men's Dress Shirts",
      description: "Rugged denim shirt with a modern relaxed cut",
      images: [
        "/images/sample-products/8b.png",
        "/images/sample-products/8gr.png",
      ],
      price: 5495,
      brand: "Levi's",
      rating: 4.1,
      numReviews: 9,
      stock: 11,
      isFeatured: true,
      banner: "/images/banner/banner-4.jpg",
    },
    {
      name: "Polo Sporting Stretch Shirt",
      slug: "polo-sporting-stretch-shirt",
      category: "Men's Dress Shirts",
      description: "Classic Polo style with modern comfort",
      images: [
        "/images/sample-products/p1-1.jpg",
        "/images/sample-products/p1-2.jpg",
      ],
      price: 5980,
      brand: "Polo",
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: "/images/banner/banner-1.jpg",
    },
    {
      name: "Brooks Brothers Long Sleeved Shirt",
      slug: "brooks-brothers-long-sleeved-shirt",
      category: "Men's Dress Shirts",
      description: "Timeless style and premium comfort",
      images: [
        "/images/sample-products/p2-1.jpg",
        "/images/sample-products/p2-2.jpg",
      ],
      price: 5590,
      brand: "Brooks Brothers",
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: "/images/banner/banner-2.jpg",
    },
    {
      name: "Tommy Hilfiger Classic Fit Dress Shirt",
      slug: "tommy-hilfiger-classic-fit-dress-shirt",
      category: "Men's Dress Shirts",
      description: "A perfect blend of sophistication and comfort",
      images: [
        "/images/sample-products/p3-1.jpg",
        "/images/sample-products/p3-2.jpg",
      ],
      price: 5500,
      brand: "Tommy Hilfiger",
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Calvin Klein Slim Fit Stretch Shirt",
      slug: "calvin-klein-slim-fit-stretch-shirt",
      category: "Men's Dress Shirts",
      description: "Streamlined design with flexible stretch fabric",
      images: [
        "/images/sample-products/p4-1.jpg",
        "/images/sample-products/p4-2.jpg",
      ],
      price: 3995,
      brand: "Calvin Klein",
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Polo Ralph Lauren Oxford Shirt",
      slug: "polo-ralph-lauren-oxford-shirt",
      category: "Men's Dress Shirts",
      description: "Iconic Polo design with refined oxford fabric",
      images: [
        "/images/sample-products/p5-1.jpg",
        "/images/sample-products/p5-2.jpg",
      ],
      price: 5000,
      brand: "Polo",
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Polo Classic Pink Hoodie",
      slug: "polo-classic-pink-hoodie",
      category: "Men's Sweatshirts",
      description: "Soft, stylish, and perfect for laid-back days",
      images: [
        "/images/sample-products/p6-1.jpg",
        "/images/sample-products/p6-2.jpg",
      ],
      price: 4999,
      brand: "Polo",
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: false,
      banner: null,
    },
  ],
};

export default sampleData;
